import './page.css';

export const metadata = {
    title: 'Create Next App (demo page)',
    description: 'Generated by create next app',
};

const RootLayout: React.FC<React.PropsWithChildren> = ({ children }) => <main id="next-13">{children}</main>;

export default RootLayout;
