import { type Config } from 'tailwindcss';
import colors from 'tailwindcss/colors';

export default {
    content: ['./src/**/*.{js,ts,jsx,tsx}'],
    theme: {
        colors: {
            background: 'rgb(var(--background-color-rgb) / <alpha-value>)',
            error: 'rgb(var(--error-color-rgb) / <alpha-value>)',
            info: 'rgb(var(--info-color-rgb) / <alpha-value>)',
            success: 'rgb(var(--success-color-rgb) / <alpha-value>)',
            text: 'rgb(var(--text-color-rgb) / <alpha-value>)',
            warning: 'rgb(var(--warning-color-rgb) / <alpha-value>)',
            black: 'rgb(var(--black-color-rgb) / <alpha-value>)',
            white: 'rgb(var(--white-color-rgb) / <alpha-value>)',

            primary: 'rgb(var(--primary-color-rgb) / <alpha-value>)',
            'primary-50': 'rgb(var(--primary-color-rgb-50) / <alpha-value>)',
            'primary-100': 'rgb(var(--primary-color-rgb-100) / <alpha-value>)',
            'primary-200': 'rgb(var(--primary-color-rgb-200) / <alpha-value>)',
            'primary-300': 'rgb(var(--primary-color-rgb-300) / <alpha-value>)',
            'primary-400': 'rgb(var(--primary-color-rgb-400) / <alpha-value>)',
            'primary-500': 'rgb(var(--primary-color-rgb-500) / <alpha-value>)',
            'primary-600': 'rgb(var(--primary-color-rgb-600) / <alpha-value>)',
            'primary-700': 'rgb(var(--primary-color-rgb-700) / <alpha-value>)',
            'primary-800': 'rgb(var(--primary-color-rgb-800) / <alpha-value>)',
            'primary-900': 'rgb(var(--primary-color-rgb-900) / <alpha-value>)',

            secondary: 'rgb(var(--secondary-color-rgb) / <alpha-value>)',
            'secondary-50': 'rgb(var(--secondary-color-rgb-50) / <alpha-value>)',
            'secondary-100': 'rgb(var(--secondary-color-rgb-100) / <alpha-value>)',
            'secondary-200': 'rgb(var(--secondary-color-rgb-200) / <alpha-value>)',
            'secondary-300': 'rgb(var(--secondary-color-rgb-300) / <alpha-value>)',
            'secondary-400': 'rgb(var(--secondary-color-rgb-400) / <alpha-value>)',
            'secondary-500': 'rgb(var(--secondary-color-rgb-500) / <alpha-value>)',
            'secondary-600': 'rgb(var(--secondary-color-rgb-600) / <alpha-value>)',
            'secondary-700': 'rgb(var(--secondary-color-rgb-700) / <alpha-value>)',
            'secondary-800': 'rgb(var(--secondary-color-rgb-800) / <alpha-value>)',
            'secondary-900': 'rgb(var(--secondary-color-rgb-900) / <alpha-value>)',
        },
        extend: {
            typography: {
                primary: {
                    css: {
                        '--tw-prose-body': 'rgb(var(--primary-color-rgb-800))',
                        '--tw-prose-headings': 'rgb(var(--primary-color-rgb-900))',
                        '--tw-prose-lead': 'rgb(var(--primary-color-rgb-700))',
                        '--tw-prose-links': 'rgb(var(--primary-color-rgb-900))',
                        '--tw-prose-bold': 'rgb(var(--primary-color-rgb-900))',
                        '--tw-prose-counters': 'rgb(var(--primary-color-rgb-600))',
                        '--tw-prose-bullets': 'rgb(var(--primary-color-rgb-400))',
                        '--tw-prose-hr': 'rgb(var(--primary-color-rgb-300))',
                        '--tw-prose-quotes': 'rgb(var(--primary-color-rgb-900))',
                        '--tw-prose-quote-borders': 'rgb(var(--primary-color-rgb-300))',
                        '--tw-prose-captions': 'rgb(var(--primary-color-rgb-700))',
                        '--tw-prose-code': 'rgb(var(--primary-color-rgb-900))',
                        '--tw-prose-pre-code': 'rgb(var(--primary-color-rgb-100))',
                        '--tw-prose-pre-bg': 'rgb(var(--primary-color-rgb-900))',
                        '--tw-prose-th-borders': 'rgb(var(--primary-color-rgb-300))',
                        '--tw-prose-td-borders': 'rgb(var(--primary-color-rgb-200))',
                        '--tw-prose-invert-body': 'rgb(var(--primary-color-rgb-200))',
                        '--tw-prose-invert-headings': 'rgb(var(--white-color-rgb))',
                        '--tw-prose-invert-lead': 'rgb(var(--primary-color-rgb-300))',
                        '--tw-prose-invert-links': 'rgb(var(--white-color-rgb))',
                        '--tw-prose-invert-bold': 'rgb(var(--white-color-rgb))',
                        '--tw-prose-invert-counters': 'rgb(var(--primary-color-rgb-400))',
                        '--tw-prose-invert-bullets': 'rgb(var(--primary-color-rgb-600))',
                        '--tw-prose-invert-hr': 'rgb(var(--primary-color-rgb-700))',
                        '--tw-prose-invert-quotes': 'rgb(var(--primary-color-rgb-100))',
                        '--tw-prose-invert-quote-borders': 'rgb(var(--primary-color-rgb-700))',
                        '--tw-prose-invert-captions': 'rgb(var(--primary-color-rgb-400))',
                        '--tw-prose-invert-code': 'rgb(var(--white-color-rgb))',
                        '--tw-prose-invert-pre-code': 'rgb(var(--primary-color-rgb-300))',
                        '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
                        '--tw-prose-invert-th-borders': 'rgb(var(--primary-color-rgb-600))',
                        '--tw-prose-invert-td-borders': 'rgb(var(--primary-color-rgb-700))',
                    },
                },
                secondary: {
                    css: {
                        '--tw-prose-body': 'rgb(var(--secondary-color-rgb-800))',
                        '--tw-prose-headings': 'rgb(var(--secondary-color-rgb-900))',
                        '--tw-prose-lead': 'rgb(var(--secondary-color-rgb-700))',
                        '--tw-prose-links': 'rgb(var(--secondary-color-rgb-900))',
                        '--tw-prose-bold': 'rgb(var(--secondary-color-rgb-900))',
                        '--tw-prose-counters': 'rgb(var(--secondary-color-rgb-600))',
                        '--tw-prose-bullets': 'rgb(var(--secondary-color-rgb-400))',
                        '--tw-prose-hr': 'rgb(var(--secondary-color-rgb-300))',
                        '--tw-prose-quotes': 'rgb(var(--secondary-color-rgb-900))',
                        '--tw-prose-quote-borders': 'rgb(var(--secondary-color-rgb-300))',
                        '--tw-prose-captions': 'rgb(var(--secondary-color-rgb-700))',
                        '--tw-prose-code': 'rgb(var(--secondary-color-rgb-900))',
                        '--tw-prose-pre-code': 'rgb(var(--secondary-color-rgb-100))',
                        '--tw-prose-pre-bg': 'rgb(var(--secondary-color-rgb-900))',
                        '--tw-prose-th-borders': 'rgb(var(--secondary-color-rgb-300))',
                        '--tw-prose-td-borders': 'rgb(var(--secondary-color-rgb-200))',
                        '--tw-prose-invert-body': 'rgb(var(--secondary-color-rgb-200))',
                        '--tw-prose-invert-headings': 'rgb(var(--white-color-rgb))',
                        '--tw-prose-invert-lead': 'rgb(var(--secondary-color-rgb-300))',
                        '--tw-prose-invert-links': 'rgb(var(--white-color-rgb))',
                        '--tw-prose-invert-bold': 'rgb(var(--white-color-rgb))',
                        '--tw-prose-invert-counters': 'rgb(var(--secondary-color-rgb-400))',
                        '--tw-prose-invert-bullets': 'rgb(var(--secondary-color-rgb-600))',
                        '--tw-prose-invert-hr': 'rgb(var(--secondary-color-rgb-700))',
                        '--tw-prose-invert-quotes': 'rgb(var(--secondary-color-rgb-100))',
                        '--tw-prose-invert-quote-borders': 'rgb(var(--secondary-color-rgb-700))',
                        '--tw-prose-invert-captions': 'rgb(var(--secondary-color-rgb-400))',
                        '--tw-prose-invert-code': 'rgb(var(--white-color-rgb))',
                        '--tw-prose-invert-pre-code': 'rgb(var(--secondary-color-rgb-300))',
                        '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
                        '--tw-prose-invert-th-borders': 'rgb(var(--secondary-color-rgb-600))',
                        '--tw-prose-invert-td-borders': 'rgb(var(--secondary-color-rgb-700))',
                    },
                },
            },
        },
    },
    plugins: [require('@tailwindcss/typography')],
} satisfies Config;
