import type { Metadata } from 'next';

import { Header } from './_components';

export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
};

export default function RootDashboardLayout({ children }: { children: React.ReactNode }) {
    return (
        <>
            <Header />
            {children}
        </>
    );
}
